name: 'Feishu Workflow'
description: 'Use GitHub action in your feishu workflow'
author: 'ButterCam'
inputs:
  url:
    description: 'web hook url'
    default: 'default value if applicable'
    required: true
  content:
    required: true
    description: the msg content

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'green'
  icon: 'message-square'
